#!/bin/sh

i3-msg workspace 1
i3-msg move workspace to output eDP1
i3-msg workspace 2
i3-msg move workspace to output DP2-2
i3-msg workspace 3
i3-msg move workspace to output DP2-2
i3-msg workspace 4
i3-msg move workspace to output DP2-2
i3-msg workspace 5
i3-msg move workspace to output DP2-1
i3-msg workspace 2
i3-msg workspace 1

init-keyboard
