#!/bin/sh

i3-msg workspace 1
sleep 0.1
i3-msg move workspace to output eDP1
sleep 0.1
i3-msg workspace 2
sleep 0.1
i3-msg move workspace to output DP2-2
sleep 0.1
i3-msg workspace 3
sleep 0.1
i3-msg move workspace to output DP2-2
sleep 0.1
i3-msg workspace 4
sleep 0.1
i3-msg move workspace to output DP2-2
sleep 0.1
i3-msg workspace 5
sleep 0.1
i3-msg move workspace to output DP2-1
sleep 0.1
i3-msg workspace 2
sleep 0.1
i3-msg workspace 1
sleep 0.1

init-keyboard
