#!/usr/bin/env bash

set -eu -o pipefail

notify-send -t 3000 "Starting server backup..."

export SSHPASS="$(gopass show blinry.org/root)"

sudo -E rsync -avvXAh -zz --partial --delete --info=progress2 -e "sshpass -e ssh" root@blinry.org:/ /home/blinry/permanent/backups/blinry.org/ --exclude={/dev/*,/proc/*,/sys/*,/tmp/*,/run/*,/mnt/*,/lost+found,/home/blinry/tmp/*,/home/blinry/Maildir/*,/home/blinry/permanent/backups/thinkerbell/*} && notify-send -t 3000 "Finished server backup." || notify-send -u critical "Server backup failed or interrupted."
