#!/usr/bin/env bash

set -eu -o pipefail

notify-send -t 3000 "Starting notebook backup..."

borgmatic -p -C && notify-send -t 3000 "Finished notebook backup." || notify-send -u critical "Notebook backup failed or interrupted."
