#!/usr/bin/env bash

set -eu -o pipefail

notify-send -t 3000 "Starting notebook backup..."

cd ~/permanent/restic/thinkerbell/ && ./backup && notify-send -t 3000 "Finished notebook backup." || notify-send -u critical "Notebook backup failed."
