#!/bin/sh

PREFIX=/sys/class/power_supply
MINUTES=0
MINUTES=0
RATE=0
SYMBOL="?"
POWER="?"


for BAT in $PREFIX/BAT*; do
    P=$(cat $BAT/power_now)
    if [ $P != "0" ]; then
        POWER=$P
    fi
done

for BAT in $PREFIX/BAT*; do
    if [ $(cat $BAT/status) = "Charging" ]; then
        SYMBOL="+"
    elif [ $(cat $BAT/status) = "Discharging" ]; then
        SYMBOL="-"
    fi
    MINUTES=$(($MINUTES + 60*$(cat $BAT/energy_now)))
done

if [ "$SYMBOL" = "?" ]; then
    echo full
    exit
fi

if [ "$POWER" = "?" ]; then
    echo '???'
    exit
fi

MINUTES=$(($MINUTES / $POWER))

if [ "$MINUTES" -lt "10" ]; then
    if [ "$SYMBOL" = "-" ]; then
        notify-send -u critical "Battery remaining: $MINUTES min"
    fi
fi

echo $(printf %1d $(($MINUTES/60))):$(printf %02d $(($MINUTES % 60)))$SYMBOL
