#!/bin/bash

xrandr --output eDP1 --pos 640x2160
xrandr --output eDP1 --pos 640x2160 --output DP2-1 --mode 3840x2160 --pos 0x0 --primary

i3-msg workspace 1
i3-msg move workspace to output eDP1
i3-msg workspace 2
i3-msg move workspace to output DP2-1
i3-msg for_window [class="termite"] move window to workspace 1
i3-msg for_window [class="chromium"] move window to workspace 2
