#!/bin/bash

cd ~/permanent/homepage || exit

urxvt -e bundle exec nanoc live &

if [ -n "$1" ]; then
    DIR="content/$1"
    mkdir -p "$DIR"
    urxvt -cd "$HOME/permanent/homepage/$DIR" -e fish -c "vim index.md; fish"&
    xdg-open "http://localhost:3000/$1/"
else
    urxvt -cd "$HOME/permanent/homepage/" &
    xdg-open "http://localhost:3000/"
fi

