#!/usr/bin/env bash

set -eu -o pipefail

cd ~/permanent/homepage || exit

$TERMINAL -e fish -c "nanoc live" &

if [ -z "${1+x}" ]; then
    $TERMINAL --working-directory "$HOME/permanent/homepage/" &
    xdg-open "http://localhost:3000/"
else
    DIR="content/$1"
    mkdir -p "$DIR"
    $TERMINAL --working-directory "$HOME/permanent/homepage/$DIR" -e fish -c "vim index.md; fish" &
    xdg-open "http://localhost:3000/$1/"
fi

