#!/usr/bin/env bash

set -eu -o pipefail

# Use the whole area of the touchpad for scrolling.
synclient VertEdgeScroll=1
synclient LeftEdge=0
synclient RightEdge=0
synclient VertScrollDelta=20
synclient HorizScrollDelta=20
synclient VertHysteresis=0
synclient HorizHysteresis=0
synclient FingerLow=1
synclient FingerHigh=5
