#!/usr/bin/env bash

set -u -o pipefail

echo "Before: $(mlist ~/permanent/mail/INBOX | wc -l) mails"

{
    mlist ~/permanent/mail/INBOX | magrep -d "subject:Wir haben Neuigkeiten für Sie" # ING
    mlist ~/permanent/mail/INBOX | magrep -d "subject:replied to your post in r" # Reddit
    mlist ~/permanent/mail/INBOX | magrep -d "subject:replied to your comment in r" # Reddit
    mlist ~/permanent/mail/INBOX | magrep -d "subject:\[haecksen\]"
    mlist ~/permanent/mail/INBOX | magrep -d "subject:\[TinyLetter\] You have a new subscriber"
    mlist ~/permanent/mail/INBOX | magrep -d "subject:\[poly-de\]"
    mlist ~/permanent/mail/INBOX | magrep -d "subject:Beleg.*Ihre Zahlung an" # PayPal
    mlist ~/permanent/mail/INBOX | magrep -d "subject:Sie haben eine Zahlung an" # PayPal
    mlist ~/permanent/mail/INBOX | magrep -d "subject:Bestäigung Ihrer Zahlung an"
    mlist ~/permanent/mail/INBOX | magrep -d "subject:Nutzer-Anfrage zu deiner Anzeige"
    mlist ~/permanent/mail/INBOX | magrep -d "subject:new roles\$"
    mlist ~/permanent/mail/INBOX | magrep -d "subject:EA Forum Digest"

    mlist ~/permanent/mail/INBOX | magrep -d "from:foodsharing.de"
    mlist ~/permanent/mail/INBOX | magrep -d "from:foodsharing.network"
    mlist ~/permanent/mail/INBOX | magrep -d "from:notifications.github.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:noreply@github.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:info.printful.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:newsletter.printful.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:updates@newsletter.printful.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:Zulip-Benachrichtigungen"
    mlist ~/permanent/mail/INBOX | magrep -d "from:rocketchat@haecksen.org"
    mlist ~/permanent/mail/INBOX | magrep -d "from:info@mail.bahncard.bahn.de"
    mlist ~/permanent/mail/INBOX | magrep -d "from:noreply@youtube.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:no-reply@twitch.tv"
    mlist ~/permanent/mail/INBOX | magrep -d "from:notifications@github.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:gitlab@mg.gitlab.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:googlealerts-noreply@google.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:news@mg2.metaculus.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:notifications@mg2.metaculus.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:sc-noreply@google.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:OkCupid"
    mlist ~/permanent/mail/INBOX | magrep -d "from:patreon.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:prototypefund.de"
    mlist ~/permanent/mail/INBOX | magrep -d "from:rechnungsstelle@1und1.de"
    mlist ~/permanent/mail/INBOX | magrep -d "from:noreply@deutschebahn.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:no-reply@deutschepost.de"
    mlist ~/permanent/mail/INBOX | magrep -d "from:versandbestaetigung@amazon.de"
    mlist ~/permanent/mail/INBOX | magrep -d "from:bestellbestaetigung@amazon.de"
    mlist ~/permanent/mail/INBOX | magrep -d "from:airbnb.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:dhl.de"
    mlist ~/permanent/mail/INBOX | magrep -d "from:hinative.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:cronometer.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:arztkonsultation.de"
    mlist ~/permanent/mail/INBOX | magrep -d "from:zoom.us"
    mlist ~/permanent/mail/INBOX | magrep -d "from:hvv-switch.de"
    mlist ~/permanent/mail/INBOX | magrep -d "from:ebay.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:discord.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:steadyhq.com"
    mlist ~/permanent/mail/INBOX | magrep -d "from:strava.com"

    mlist ~/permanent/mail/INBOX | magrep -d "to:lists.community.recurse.com"

} | mrefile ~/permanent/mail/Archive

echo "After: $(mlist ~/permanent/mail/INBOX | wc -l) mails"
