#!/bin/sh

sudo modprobe psmouse

# In my setup, it takes the mouse devices ~8 seconds to wake up.
sleep 10

# Use the whole area of the touchpad for scrolling.
synclient VertEdgeScroll=1
synclient LeftEdge=0
synclient RightEdge=0
