#!/usr/bin/env bash

set -eu -o pipefail

xinput map-to-output $(xinput list --id-only "Wacom Pen and multitouch sensor Pen stylus") eDP1
xinput map-to-output $(xinput list --id-only "Wacom Pen and multitouch sensor Pen eraser") eDP1
xinput map-to-output $(xinput list --id-only "Wacom Pen and multitouch sensor Finger touch") eDP1
