#!/bin/bash

cd $HOME/permanent/pf2-wiki

#lastcommittime=$(git show --format="%ct" -s)
#nowtime=$(date +%s)
#
#if [ $(($nowtime - $lastcommittime)) -gt $((60*60*24)) ]; then
#    echo "Autocommit"
#    git add -A
#    git commit -m "Autocommit"
#fi

cmd=$1
shift

case $cmd in
    e|edit)
        if [ "$*" ]; then
            "$EDITOR" "$*"
        else
            "$EDITOR" Startseite
        fi
        ;;
    s|search)
        $0 t $*
        echo
        $0 f $*
        ;;
    b|backlinks)
        $0 f \\[$*\\]
        ;;
    t|title)
        ls | grep --color=auto -i "$*"
        ;;
    f|fulltext)
        egrep --color=auto -in "$*" *
        ;;
    o|orphans)
        for word in *; do
            if [ -z "`$0 b $word`" ]; then
                echo $word
            fi
        done
        ;;
    r|random)
        $0 e "$(ls | sort -R | head -1)"
        ;;
    *)
        $0 e $cmd $*
        ;;
esac
