#!/usr/bin/env bash

set -u -o pipefail

AUDIODEVICE=$(pactl get-default-source)

ffmpeg -threads 0 -f pulse -itsoffset "-1.8" -i "$AUDIODEVICE.monitor" -c:a aac "$HOME"/tmp/screencast-$(date +%F_%T).mp4
