#!/bin/sh

if hash todo-status 2>/dev/null; then
    todo="`todo-status` │ "
else
    todo=""
fi
np=`test -n "$(mpc|grep '\[playing\]')" && echo "$(mpc|head -1) │ "`
volume=`amixer get 'Master' | grep -o '[0-9]\+%' | head -1 | grep -o '[0-9]\+'`
mute=`test -n "$(amixer get 'Master'|grep '\[on\]')" && echo ♫ || echo ✗`
batt=`battery-status`
date=`date +"%Y-%m-%d"`
time_local=`date +"%H:%M"`

# See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
time_ny=`LC_TIME="C" TZ="America/New_York" date +"%-I:%M %P"`
time_la=`LC_TIME="C" TZ="America/Los_Angeles" date +"%-I:%M %P"`
time_tokyo=`LC_TIME="C" TZ="Asia/Tokyo" date +"%-H:%M"`

echo "$todo$np$volume$mute │ $batt | $time_la (Los Angeles), $time_ny (New York), $time_tokyo (Tokyo) │ $date $time_local"
sleep 10
