#!/bin/sh

volume=`amixer get 'Master' | grep -o '[0-9]\+%' | head -1 | grep -o '[0-9]\+'`
mute=`test -n "$(amixer get 'Master'|grep '\[on\]')" && echo ♫ || echo ✗`
batt=`battery-status`
date=`date +"%Y-%m-%d %H:%M"`

echo $volume$mute │ $batt │ $date
