#!/bin/sh

export LC_TIME=ja_JP.UTF-8

volume=`amixer get 'Master' | grep -o '[0-9]\+%' | head -1 | grep -o '[0-9]\+'`
mute=`test -n "$(amixer get 'Master'|grep '\[on\]')" && echo ♫ || echo ♩`
ip=`ip addr show wlan0 | grep 'inet ' | cut -d' ' -f6`
batt=`battery-status`
date=`date +"%a %Y-%m-%d %H:%M"`

if [ "$ip" == "" ]; then
    ip="offline"
fi

echo $volume$mute │ $ip │ $batt │ $date
