#!/bin/sh

#ffmpeg -i "$1" -vcodec libx264 -pix_fmt yuv420p -strict -2 -acodec aac ${1%.*}-twitter.mp4

ffmpeg -i "$1" -pix_fmt yuv420p -vcodec libx264 -vf scale=1000:-2 -acodec aac -vb 1024k -minrate 1024k -maxrate 1024k -bufsize 1024k -ar 44100  -ac 2  -strict experimental -r 30 "${1%.*}-twitter.mp4"
