#!/usr/bin/env bash

set -eu -o pipefail

cd ~/permanent/wiki/

if [ -z "$*" ]; then
    PAGE="$(ls|fzf --print-query|tail -1)" || true
else
    PAGE="$*"
fi

if [ -n "$PAGE" ]; then
    "$EDITOR" "$PAGE"
fi
