#!/usr/bin/env bash

set -eu -o pipefail

# By default, disable block after 60 minutes.
MINUTES="${1:-60}"
systemd-run --user --on-active="$MINUTES"m web-unblock

sudo sed -i 's/#0/0/' /etc/hosts && notify-send -t 3000 "Distractions blocked for $MINUTES min"
