#!/usr/bin/env ruby

connected = `iwctl station wlan0 show | grep "Connected network"`

unless connected.empty?
    puts "Connected to: " + connected.strip.split("  ").last.strip
end

`iwctl station wlan0 scan`
sleep 1

networks = `iwctl station wlan0 get-networks`.lines[4..-2]
networks = networks.map do |n|
    parts =  n.split("  ")
    label = parts[2..-1].find{|n| n != ""}
    label += " [open]" if n[" open "]
    label
end

file = "/tmp/iwd-networks"
File.write(file, networks.join("\n"))

network = `cat #{file} | fzf`.chomp
network.gsub!(/ \[open\]/, "")

if network and not network.empty?
    cmd = "iwctl station wlan0 connect '#{network}\'"
    puts cmd
    system(cmd)
end
