#!/usr/bin/env bash

set -eu -o pipefail

time_ny=`LC_TIME="C" TZ="America/New_York" date +"%-I:%M %P"`
time_la=`LC_TIME="C" TZ="America/Los_Angeles" date +"%-I:%M %P"`
time_tokyo=`LC_TIME="C" TZ="Asia/Tokyo" date +"%-H:%M"`

echo "$time_la (Los Angeles), $time_ny (New York), $time_tokyo (Tokyo)"
