#!/bin/sh

if [ ! -d "$HOME/.vim/bundle/vundle" ]; then
    mkdir -p ~/.vim/bundle
    git clone git://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
else
    echo "Vundle is already installed"
fi
echo "Updating bundles..."
vim +BundleInstall! +qall
echo "Done. Have fun!"
