#!/bin/sh

if [ ! -d "$HOME/.vim/bundle/vundle" ]; then
    mkdir -p ~/.vim/bundle
    git clone git://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
else
    echo "Vundle is already installed"
fi

echo "Updating bundles..."
vim +BundleInstall! +qall

if which pacman &> /dev/null && which yaourt &> /dev/null; then
    echo "pacman and yaourt found; Installing default packages..."
    ~/.meta/install-arch-packages
fi

echo "Done. Have fun!"
